lang: pl-PL
title: Radosław Roszczyk
description: > # this means to ignore newlines until "baseurl:"
  To jest mój osobisty blog, służący wyrażaniu moich prywatnych opinii na różne tematy. Jest to również mój osobisty dziennik w&nbsp;którym dzielę się swoimi przemyśleniami oraz pomysłami dotyczącymi różnych spraw.
#permalink: ':title/'
website: https://blog.roszczyk.net
url: "https://blog.roszczyk.net"
baseurl: ""
#  url: "http://127.0.0.1:4000"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Radosław Roszczyk # add your name
author-img: radoslaw_roszczyk_192.jpg # add your photo
#about-author: I am a software developer, researcher, and academic. Always hungry to keep learning. # add description
#about-author: Thoughts, stories and ideas. Przemyślenia, historie oraz nowe koncepcje.
about-author: notatki, materiały, oraz inne przydatne rzeczy
social-twitter: rroszczyk # add your Twitter handle
#social-facebook: rroszczy # add your Facebook handle
social-github: rroszczyk # add your Github handle
social-linkedin: rroszczyk # add your Linkedin handle
#social-email: # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: "G-1J283Z0BLK" # Google Analytics (UA is legacy; set GA4 ID like G-XXXXXXXXXX when available)

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-gzip
  - jekyll-katex
  - jekyll-scholar

paginate: 8
paginate_path: "/page/:num"
permalink:             /:categories/:title/


menu:
  - title:             Blog
    url:               /
  - title:             Projekty
    url:               /projekty/
  - title:             Dydaktyka
    url:               /dydaktyka/
    
tag:  ""

collections:
  featured_tags:
    permalink:         /tags/:name/
    output:            true  

  featured_categories:
    permalink:         /:name/
    output:            true


compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]
   

gzip:
  extensions:
    - '.html'
    - '.css'
    - '.js'      

kramdown:
  math_engine:         katex
  math_engine_opts:    {}
  syntax_highlighter: rouge
  syntax_highlighter_opts:  
    default_lang: text
    css_class   : 'highlight'    
    block:
      line_numbers: false
      default_lang: text
      css_class   : 'highlight'          
    span:
      default_lang: text
      line_numbers: false     
      css_class   : 'highlight'  
  typographic_symbols:
    ndash: "&ndash;"
    mdash: "&mdash;"         

katex:
  rendering_options:
    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000"                  # errorColor  

scholar:
  style: assets/csl/ieee.csl
#  style: ieee
#  style: ieee-transactions-on-medical-imaging
  source: _bibliography
  # zamiast listy
  bibliography_list_tag: div
  bibliography_item_tag: p

  # opcjonalnie: atrybuty (np. klasy)
  bibliography_list_attributes:
    class: bibliography
  bibliography_item_attributes:
    class: bib-entry

defaults:
  # `jekyll-seo-tag` will mark collection outputs as `BlogPosting`,
  # but we want them to be `WebPage`s:
  - scope:
      type:            projects
    values:
      seo:
        type:          WebPage
  - scope:
      type:            featured_categories
    values:
      seo:
        type:          WebPage
  - scope:
      type:            featured_tags
    values:
      seo:
        type:          WebPage

exclude: ["node_modules", "vendor", "Gemfile", "Gemfile.lock", "README.md", "package.json", "yarn.lock", "gulpfile.js"]